apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: storage
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/erikandreasklokk/homelab'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'local-path-storage'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'