apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-henrikkwk
  namespace: gateway
spec:
  dnsNames:
    - "*.henrikkwk.no"
    - henrikkwk.no
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-cluster-issuer
  secretName: cert-henrikkwk
  usages:
    - digital signature
    - key encipherment
