---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAvv8VNXRPwUynSJbt5RXSErRvYB5ncWHqlXJWwt3OPSfwEyBz47gc8v5mGNkcSBD5gsxLnLrz8P0oqP07dHSA/SjZSGuRqUulu9f/hDzLvI2PAs+pJ7SAu+dnI4JlIpxKo2JNqLcZm+XTAP+j3/11iZWoqB893pmnN63cUnGleKirR+bRSVKc5Hekh9U1RvJa3mhErn/yVPHzxh9kz9/guegm7j4+AgGSvehCmU3Fv4W0veJaxsAPOr7P3W2npXpYLwdDYWyqZZhRqVsyZ/lJzOZiH6+j4UbfaILy6wrb+dlQQo9amlABGxpV66EcGVBSE1IxQyWUjd9wOge4+2nKA2kty4hF9Kar58NGzuEilgaSbc8yvEu0jRVXsT0L8gnSW/TO2N7iTkbZ/V3pvszHrAkHQBiI/EEIBzBprXb0dKX5Y5sNusIrtpAztQJTAv8xwkkcb0wQrN47WIvgcmnKM6zWbcL7E8/UoFno8TwZF8BBB3kUoApaIB2gdwFkFjebqM7IqtttbzAgToe9Lqu4hOFXgmox22lIXLD1z3+gEz/nlySPtHPnCSIUNkw9jUGacFtT4TJo7Y/9YtISaFB+IPVQ2xOICFyUfgNtr7PJUq2Owed2B/gHTjsDYc84U3hGQWZe8ZoOIaAQgxJG62aZ7EHuyARiYw7xFE3JlnAyg5sLP0GPFd/6jepEW+kwiVMfY6hp4cKtZ5xpkzyGuNOX6+WApcfWLRgq1qbYOfDlGT2JoZYf20rux4xxgV4DbCVy+8sGawqK9WTWk/Zv8vV8y2IQzge/Jcq4x/UKsEXi0dnuXqoGQhGzI0pGB2dJeRFofqvDq8RH1RkvsUIds06fRQ4EXxLsGCkhzEDXvGohXePrSsmnUXfzPjLRn8eme2x+4TdaStQ7dNBNRKQEIEBFPfZJL9lgBjZHABum5lDfj
  template:
    metadata:
      name: tunnel-credentials
      namespace: cloudflared
